CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    purchased BOOLEAN NOT NULL DEFAULT FALSE,
    priority VARCHAR(10) NOT NULL
        CHECK (priority IN ('low', 'medium', 'high'))
);

ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS purchased BOOLEAN NOT NULL DEFAULT FALSE;